# Generated by Django 2.2.12 on 2021-12-23 20:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='stage',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
