# Generated by Django 2.2.12 on 2021-12-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0002_subsession_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='stage',
        ),
    ]
