# Generated by Django 2.2.12 on 2021-12-23 20:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0003_remove_subsession_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matchesPlayed',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
