# Generated by Django 2.2.12 on 2021-12-23 20:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0005_auto_20211223_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='new_round',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
