# Generated by Django 2.2.12 on 2021-12-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0006_auto_20211223_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matchesPlayed',
        ),
    ]
