# Generated by Django 2.2.12 on 2021-12-23 22:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0007_remove_player_matchesplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='new_round',
        ),
        migrations.AddField(
            model_name='player',
            name='new_round',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
