# Generated by Django 2.2.12 on 2021-12-23 22:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0008_auto_20211223_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='new_round',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
