# Generated by Django 2.2.12 on 2021-12-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0009_auto_20211223_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='new_round',
        ),
    ]
