# Generated by Django 2.2.12 on 2021-12-24 05:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0010_remove_player_new_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='match_number',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subsession',
            name='round_in_match_number',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
