# Generated by Django 2.2.12 on 2022-01-05 22:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeatedFlip', '0011_auto_20211224_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner_choice',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
