# Generated by Django 2.2.12 on 2021-12-22 20:01

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('group_project', otree.db.models.IntegerField(default=0, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishment_group', to='otree.Session')),
            ],
            options={
                'db_table': 'punishment_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punishment_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'punishment_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('contribution', otree.db.models.IntegerField(null=True)),
                ('punished', otree.db.models.IntegerField(default=0, null=True)),
                ('first_payoff', otree.db.models.IntegerField(default=0, null=True)),
                ('final_payoff', otree.db.models.IntegerField(default=0, null=True)),
                ('actual', otree.db.models.IntegerField(default=0, null=True)),
                ('reduced', otree.db.models.IntegerField(default=0, null=True)),
                ('deduct_P1', otree.db.models.IntegerField(null=True, verbose_name='Deduct from P1:')),
                ('deduct_P2', otree.db.models.IntegerField(null=True, verbose_name='Deduct from P2:')),
                ('deduct_P3', otree.db.models.IntegerField(null=True, verbose_name='Deduct from P3:')),
                ('deduct_P4', otree.db.models.IntegerField(null=True, verbose_name='Deduct from P4:')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punishment.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishment_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishment_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment.Subsession')),
            ],
            options={
                'db_table': 'punishment_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment.Subsession'),
        ),
    ]
