# Generated by Django 2.2.12 on 2022-01-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalForm', '0004_player_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='roles',
        ),
    ]
