# Generated by Django 2.2.12 on 2022-01-06 00:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('normalForm', '0005_remove_player_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
