# Generated by Django 2.2.12 on 2022-01-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalForm', '0006_player_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
    ]
