# Generated by Django 2.2.12 on 2022-01-07 03:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('normalForm', '0011_remove_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opponent_choice',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
