# Generated by Django 2.2.12 on 2021-12-22 21:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pennies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='payoff',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
