# Generated by Django 2.2.12 on 2021-12-22 21:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pennies', '0002_player_payoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payoff',
        ),
        migrations.AddField(
            model_name='player',
            name='pennypayoff',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
