# Generated by Django 2.2.12 on 2022-01-07 03:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pennies', '0003_auto_20211222_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner_choice',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
