# Generated by Django 2.2.12 on 2021-12-22 21:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='private_tokens',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sent_tokens',
        ),
        migrations.AddField(
            model_name='player',
            name='effort',
            field=otree.db.models.CurrencyField(null=True, verbose_name='Effort'),
        ),
    ]
