# Generated by Django 2.2.12 on 2022-01-05 21:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cournot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='opp',
        ),
        migrations.AddField(
            model_name='player',
            name='opponent_production',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
