# Generated by Django 2.2.12 on 2022-01-05 22:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner_claim',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
