# Generated by Django 2.2.12 on 2022-01-05 21:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPrice_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner_bid',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='partner_value',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
