# Generated by Django 2.2.12 on 2021-12-22 23:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPrice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bid',
            field=otree.db.models.FloatField(null=True, verbose_name='Your Bid:'),
        ),
    ]
