# Generated by Django 2.2.12 on 2022-01-05 21:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPrice', '0002_auto_20211222_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner_value',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
