# Generated by Django 2.2.12 on 2021-12-24 23:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='platform',
            field=otree.db.models.FloatField(null=True, verbose_name='Your Preferences'),
        ),
    ]
