# Generated by Django 2.2.12 on 2021-12-24 23:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20211224_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first',
            field=otree.db.models.StringField(choices=[(1, 1), (2, 2), (3, 3)], max_length=10000, null=True, verbose_name='Your Preferences'),
        ),
        migrations.AlterField(
            model_name='player',
            name='second',
            field=otree.db.models.StringField(choices=[(1, 1), (2, 2), (3, 3)], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='third',
            field=otree.db.models.StringField(choices=[(1, 1), (2, 2), (3, 3)], max_length=10000, null=True),
        ),
    ]
