# Generated by Django 2.2.12 on 2021-12-24 23:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20211224_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='First Preference'),
        ),
        migrations.AlterField(
            model_name='player',
            name='second',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='Second Preference'),
        ),
        migrations.AlterField(
            model_name='player',
            name='third',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True, verbose_name='Third Preference'),
        ),
    ]
