# Generated by Django 2.2.12 on 2021-12-25 02:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20211224_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Tie',
        ),
        migrations.RemoveField(
            model_name='player',
            name='opponent_platform',
        ),
        migrations.RemoveField(
            model_name='player',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='player',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='winner',
        ),
        migrations.AddField(
            model_name='group',
            name='round',
            field=otree.db.models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='s1',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='s2',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='s3',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='match',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='student',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
