# Generated by Django 2.2.12 on 2021-12-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20211224_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='group',
            name='s3',
        ),
    ]
