# Generated by Django 2.2.12 on 2022-01-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_auto_20211225_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='student',
        ),
    ]
