# Generated by Django 2.2.12 on 2022-01-06 22:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner_price',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
