# Generated by Django 2.2.12 on 2022-01-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20211222_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='voters',
        ),
    ]
