# Generated by Django 2.2.12 on 2021-12-22 20:01

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('type', otree.db.models.StringField(max_length=10000, null=True)),
                ('group_pot', otree.db.models.FloatField(default=0, null=True)),
                ('playerA', otree.db.models.StringField(max_length=10000, null=True)),
                ('playerB', otree.db.models.StringField(max_length=10000, null=True)),
                ('playerC', otree.db.models.StringField(max_length=10000, null=True)),
                ('A_cont', otree.db.models.FloatField(null=True)),
                ('B_cont', otree.db.models.FloatField(null=True)),
                ('C_cont', otree.db.models.FloatField(null=True)),
                ('A_payoff', otree.db.models.FloatField(null=True)),
                ('B_payoff', otree.db.models.FloatField(null=True)),
                ('C_payoff', otree.db.models.FloatField(null=True)),
                ('A_punished', otree.db.models.FloatField(default=0, null=True)),
                ('B_punished', otree.db.models.FloatField(default=0, null=True)),
                ('C_punished', otree.db.models.FloatField(default=0, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgg_group', to='otree.Session')),
            ],
            options={
                'db_table': 'PGG_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('conditions', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pgg_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'PGG_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('original_label', otree.db.models.StringField(max_length=10000, null=True)),
                ('first_payoff', otree.db.models.FloatField(default=0, null=True)),
                ('final_payoff', otree.db.models.FloatField(default=0, null=True)),
                ('us_payoff', otree.db.models.FloatField(default=0, null=True)),
                ('base_combo_payoff', otree.db.models.FloatField(default=0, null=True)),
                ('punished', otree.db.models.FloatField(null=True)),
                ('round_payoff', otree.db.models.FloatField(default=0, null=True)),
                ('affiliation', otree.db.models.StringField(choices=[('Democrat', 'Democrat'), ('Republican', 'Republican')], max_length=10000, null=True, verbose_name='')),
                ('label', otree.db.models.StringField(max_length=10000, null=True)),
                ('group_contribution', otree.db.models.FloatField(null=True, verbose_name='Your Contribution to the Group Project:')),
                ('individual_share', otree.db.models.FloatField(null=True)),
                ('kept', otree.db.models.FloatField(null=True)),
                ('choice', otree.db.models.StringField(choices=[('Participate', 'Participate'), ('Do Not Participate', 'Do Not Participate')], max_length=10000, null=True)),
                ('punishA', otree.db.models.FloatField(null=True, verbose_name='')),
                ('punishB', otree.db.models.FloatField(null=True, verbose_name='')),
                ('punishC', otree.db.models.FloatField(null=True, verbose_name='')),
                ('reduce', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PGG.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgg_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgg_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGG.Subsession')),
            ],
            options={
                'db_table': 'PGG_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGG.Subsession'),
        ),
    ]
