# Generated by Django 2.2.12 on 2021-12-22 22:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eleven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='request',
            field=otree.db.models.IntegerField(null=True, verbose_name='Please enter an amount from 11 to 20.'),
        ),
    ]
