# Generated by Django 2.2.12 on 2022-01-05 21:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('eleven', '0002_auto_20211222_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='partner_request',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
