# Generated by Django 2.2.12 on 2022-01-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0002_player_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
    ]
